language: php

php:
    - 5.3
    - 5.4

env:
    global:
        - PLUGINSLUG=podcast-player-widget
        - MAINFILE=plugin.php
    matrix:
        - WP_VERSION=latest WP_MULTISITE=0
        - WP_VERSION=latest WP_MULTISITE=1
        - WP_VERSION=3.7 WP_MULTISITE=0
        - WP_VERSION=3.7 WP_MULTISITE=1

before_script:
    - curl -O https://raw.githubusercontent.com/ycfreeman/wp-plugin-template/master/deploy-wordpress-plugin.sh
    - curl -O https://raw.githubusercontent.com/wp-cli/wp-cli/master/templates/install-wp-tests.sh
    - curl -Lo travis_after_all.py https://raw.github.com/Javierchik/travis_after_all/master/travis_after_all.py
    - bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
    - phpunit

after_success:
    - python travis_after_all.py
    - export $(cat .to_export_back)
    - |
        if [ "$BUILD_LEADER" = "YES" ]; then
          if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
            if ([ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]); then
              echo tag=$TRAVIS_TAG;
              bash deploy-wordpress-plugin.sh $PLUGINSLUG $MAINFILE $TRAVIS_TAG $SVNUSER $SVNPASS;
            fi
          else
            echo "Some jobs failed"
          fi
        fi
after_failure:
    - python travis_after_all.py
    - export $(cat .to_export_back)
    - |
        if [ "$BUILD_LEADER" = "YES" ]; then
          if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
            echo "All jobs failed"
          else
            echo "Some jobs failed"
          fi
        fi
after_script:
    - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
